// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDttF2BVLdUusdmQe3sWdQKDm1mZ1T_pHg',
    appId: '1:648236619676:web:6645578bdc88c52a83da59',
    messagingSenderId: '648236619676',
    projectId: 'welllog-84db4',
    authDomain: 'welllog-84db4.firebaseapp.com',
    storageBucket: 'welllog-84db4.firebasestorage.app',
    measurementId: 'G-YKF220EE0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD13qX-5sAt88pOBtqhpgR5yj4jty0dBVE',
    appId: '1:648236619676:android:585399c12de7cc2683da59',
    messagingSenderId: '648236619676',
    projectId: 'welllog-84db4',
    storageBucket: 'welllog-84db4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtzVTQm4XE2RdqrTnIzlCeFCcoveT6vaw',
    appId: '1:648236619676:ios:0cc008c69f1ad33a83da59',
    messagingSenderId: '648236619676',
    projectId: 'welllog-84db4',
    storageBucket: 'welllog-84db4.firebasestorage.app',
    iosBundleId: 'com.example.welllog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtzVTQm4XE2RdqrTnIzlCeFCcoveT6vaw',
    appId: '1:648236619676:ios:0cc008c69f1ad33a83da59',
    messagingSenderId: '648236619676',
    projectId: 'welllog-84db4',
    storageBucket: 'welllog-84db4.firebasestorage.app',
    iosBundleId: 'com.example.welllog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDttF2BVLdUusdmQe3sWdQKDm1mZ1T_pHg',
    appId: '1:648236619676:web:9567cb8fbc1bc6f883da59',
    messagingSenderId: '648236619676',
    projectId: 'welllog-84db4',
    authDomain: 'welllog-84db4.firebaseapp.com',
    storageBucket: 'welllog-84db4.firebasestorage.app',
    measurementId: 'G-CN0K0B8DCF',
  );
}
